export const activitiesContent = {
  title: 'Our Activities & Programs',
  subtitle: 'Community Health Initiatives',
  activities: [
    {
      id: 1,
      title: 'Free Health Camps',
      description: 'Regular health screening camps in local communities providing free check-ups and consultations.',
      image: 'https://images.pexels.com/photos/7176307/pexels-photo-7176307.jpeg?auto=compress&cs=tinysrgb&w=800',
      date: 'Monthly - First Saturday',
      time: '9:00 AM - 2:00 PM',
    },
    {
      id: 2,
      title: 'Health Awareness Programs',
      description: 'Educational workshops on disease prevention, nutrition, and healthy lifestyle choices.',
      image: 'https://images.pexels.com/photos/7551662/pexels-photo-7551662.jpeg?auto=compress&cs=tinysrgb&w=800',
      date: 'Weekly - Every Wednesday',
      time: '4:00 PM - 6:00 PM',
    },
    {
      id: 3,
      title: 'Blood Donation Drives',
      description: 'Organized blood donation camps to maintain adequate blood supply for emergencies.',
      image: 'https://images.pexels.com/photos/6823567/pexels-photo-6823567.jpeg?auto=compress&cs=tinysrgb&w=800',
      date: 'Quarterly',
      time: '10:00 AM - 4:00 PM',
    },
    {
      id: 4,
      title: 'Vaccination Programs',
      description: 'Child and adult vaccination programs to prevent infectious diseases.',
      image: 'https://images.pexels.com/photos/8460157/pexels-photo-8460157.jpeg?auto=compress&cs=tinysrgb&w=800',
      date: 'Daily',
      time: '9:00 AM - 1:00 PM',
    },
    {
      id: 5,
      title: 'Senior Citizen Care',
      description: 'Special health check-up packages and wellness programs for senior citizens.',
      image: 'https://images.pexels.com/photos/7551608/pexels-photo-7551608.jpeg?auto=compress&cs=tinysrgb&w=800',
      date: 'Monthly - Last Friday',
      time: '10:00 AM - 3:00 PM',
    },
    {
      id: 6,
      title: 'Mental Health Support',
      description: 'Counseling sessions and support groups for mental health and wellness.',
      image: 'https://images.pexels.com/photos/7176325/pexels-photo-7176325.jpeg?auto=compress&cs=tinysrgb&w=800',
      date: 'Weekly - Monday & Thursday',
      time: '3:00 PM - 7:00 PM',
    },
  ],
};
