export const doctorsContent = {
  title: 'Our Medical Team',
  subtitle: 'Meet Our Expert Doctors',
  categories: [
    {
      id: 'fulltime',
      name: 'Full-Time Doctors',
      description: 'Available throughout the week for comprehensive patient care',
      doctors: [
        {
          id: 1,
          name: 'Dr. Sarah Johnson',
          specialty: 'Cardiology',
          qualification: 'MD, FACC',
          experience: '15 years',
          image: 'https://images.pexels.com/photos/5327585/pexels-photo-5327585.jpeg?auto=compress&cs=tinysrgb&w=600',
          availability: 'Mon - Sat, 9:00 AM - 5:00 PM',
        },
        {
          id: 2,
          name: 'Dr. Michael Chen',
          specialty: 'Neurology',
          qualification: 'MD, PhD',
          experience: '20 years',
          image: 'https://images.pexels.com/photos/5452293/pexels-photo-5452293.jpeg?auto=compress&cs=tinysrgb&w=600',
          availability: 'Mon - Sat, 10:00 AM - 6:00 PM',
        },
        {
          id: 3,
          name: 'Dr. Emily Rodriguez',
          specialty: 'Pediatrics',
          qualification: 'MD, FAAP',
          experience: '12 years',
          image: 'https://images.pexels.com/photos/5327656/pexels-photo-5327656.jpeg?auto=compress&cs=tinysrgb&w=600',
          availability: 'Mon - Fri, 8:00 AM - 4:00 PM',
        },
        {
          id: 4,
          name: 'Dr. James Wilson',
          specialty: 'Orthopedics',
          qualification: 'MD, FAAOS',
          experience: '18 years',
          image: 'https://images.pexels.com/photos/5452201/pexels-photo-5452201.jpeg?auto=compress&cs=tinysrgb&w=600',
          availability: 'Mon - Sat, 9:00 AM - 5:00 PM',
        },
      ],
    },
    {
      id: 'visiting',
      name: 'Visiting Doctors',
      description: 'Specialist consultants available on scheduled days',
      doctors: [
        {
          id: 5,
          name: 'Dr. Patricia Anderson',
          specialty: 'Oncology',
          qualification: 'MD, FASCO',
          experience: '25 years',
          image: 'https://images.pexels.com/photos/5327580/pexels-photo-5327580.jpeg?auto=compress&cs=tinysrgb&w=600',
          availability: 'Wed & Sat, 2:00 PM - 6:00 PM',
        },
        {
          id: 6,
          name: 'Dr. Robert Martinez',
          specialty: 'Dermatology',
          qualification: 'MD, FAAD',
          experience: '14 years',
          image: 'https://images.pexels.com/photos/5452268/pexels-photo-5452268.jpeg?auto=compress&cs=tinysrgb&w=600',
          availability: 'Tue & Thu, 3:00 PM - 7:00 PM',
        },
      ],
    },
    {
      id: 'departments',
      name: 'Department-Wise Specialists',
      description: 'Specialized care across multiple departments',
      departments: [
        {
          id: 1,
          name: 'Emergency Medicine',
          doctors: ['Dr. Lisa Thompson', 'Dr. David Lee'],
          availability: '24/7',
        },
        {
          id: 2,
          name: 'General Surgery',
          doctors: ['Dr. Jennifer White', 'Dr. Mark Brown'],
          availability: 'Mon - Sat, 9:00 AM - 5:00 PM',
        },
        {
          id: 3,
          name: 'Internal Medicine',
          doctors: ['Dr. Amanda Garcia', 'Dr. Christopher Taylor'],
          availability: 'Mon - Fri, 8:00 AM - 4:00 PM',
        },
        {
          id: 4,
          name: 'Radiology',
          doctors: ['Dr. Kevin Harris', 'Dr. Michelle Clark'],
          availability: '24/7',
        },
      ],
    },
  ],
};
